[project]
name = "pihole-long-term-stats"
version = "0.1.0"
description = "Dashboard for visualizing long-term DNS query data from Pi-hole"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dash>=3.0.4",
    "pandas>=2.2.3",
    "plotly>=6.0.1",
]
